project_name: tart-guest-agent

before:
  hooks:
    - go mod download

builds:
  - main: cmd/main.go
    ldflags: >
      -X github.com/cirruslabs/tart-guest-agent/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/tart-guest-agent/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: tart-guest-agent
    ids:
      - binary
    repository:
      owner: cirruslabs
      name: homebrew-cli
    homepage: https://github.com/cirruslabs/tart-guest-agent
    license: FSL-1.1-Apache-2.0
    description: Guest agent for Tart VMs
    skip_upload: auto
    install: |
      bin.install "tart-guest-agent"

nfpms:
  - package_name: tart-guest-agent
    vendor: Cirrus Labs, Inc.
    homepage: https://github.com/cirruslabs/tart-guest-agent
    maintainer: support@cirruslabs.org
    description: Guest agent for Tart VMs
    section: misc
    formats:
      - deb
      - rpm

furies:
  - account: cirruslabs
