---
version: 2
project_name: tart-guest-agent

before:
  hooks:
    - go mod download

builds:
  - id: darwin
    main: cmd/main.go
    flags: >-
      -trimpath
    ldflags: >-
      -s -w
      -X github.com/cirruslabs/tart-guest-agent/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/tart-guest-agent/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64

  - id: linux
    main: cmd/main.go
    flags: >-
      -trimpath
    ldflags: >-
      -s -w
      -X github.com/cirruslabs/tart-guest-agent/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/tart-guest-agent/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64

universal_binaries:
  - replace: true
    ids:
      - darwin

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz

release:
  prerelease: auto

brews:
  - name: "{{ .ProjectName }}"
    repository:
      owner: cirruslabs
      name: homebrew-cli
    homepage: https://github.com/cirruslabs/tart-guest-agent
    license: FSL-1.1-Apache-2.0
    description: Guest agent for Tart VMs
    skip_upload: auto

nfpms:
  - package_name: "{{ .ProjectName }}"
    vendor: Cirrus Labs, Inc.
    homepage: https://github.com/cirruslabs/tart-guest-agent
    maintainer: support@cirruslabs.org
    description: Guest agent for Tart VMs
    section: misc
    formats:
      - apk
      - deb
      - rpm

furies:
  - account: cirruslabs
