// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: rpc/agent.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalRequest_Signal int32

const (
	SignalRequest_SIGNAL_UNSPECIFIED SignalRequest_Signal = 0
	SignalRequest_SIGNAL_SIGTERM     SignalRequest_Signal = 1
	SignalRequest_SIGNAL_SIGKILL     SignalRequest_Signal = 2
)

// Enum value maps for SignalRequest_Signal.
var (
	SignalRequest_Signal_name = map[int32]string{
		0: "SIGNAL_UNSPECIFIED",
		1: "SIGNAL_SIGTERM",
		2: "SIGNAL_SIGKILL",
	}
	SignalRequest_Signal_value = map[string]int32{
		"SIGNAL_UNSPECIFIED": 0,
		"SIGNAL_SIGTERM":     1,
		"SIGNAL_SIGKILL":     2,
	}
)

func (x SignalRequest_Signal) Enum() *SignalRequest_Signal {
	p := new(SignalRequest_Signal)
	*p = x
	return p
}

func (x SignalRequest_Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalRequest_Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_agent_proto_enumTypes[0].Descriptor()
}

func (SignalRequest_Signal) Type() protoreflect.EnumType {
	return &file_rpc_agent_proto_enumTypes[0]
}

func (x SignalRequest_Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalRequest_Signal.Descriptor instead.
func (SignalRequest_Signal) EnumDescriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{6, 0}
}

type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ExecRequest_Command_
	//	*ExecRequest_StandardInput
	//	*ExecRequest_TerminalResize
	Type          isExecRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_rpc_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetType() isExecRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ExecRequest) GetCommand() *ExecRequest_Command {
	if x != nil {
		if x, ok := x.Type.(*ExecRequest_Command_); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ExecRequest) GetStandardInput() *IOChunk {
	if x != nil {
		if x, ok := x.Type.(*ExecRequest_StandardInput); ok {
			return x.StandardInput
		}
	}
	return nil
}

func (x *ExecRequest) GetTerminalResize() *TerminalSize {
	if x != nil {
		if x, ok := x.Type.(*ExecRequest_TerminalResize); ok {
			return x.TerminalResize
		}
	}
	return nil
}

type isExecRequest_Type interface {
	isExecRequest_Type()
}

type ExecRequest_Command_ struct {
	Command *ExecRequest_Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ExecRequest_StandardInput struct {
	StandardInput *IOChunk `protobuf:"bytes,2,opt,name=standard_input,json=standardInput,proto3,oneof"`
}

type ExecRequest_TerminalResize struct {
	TerminalResize *TerminalSize `protobuf:"bytes,3,opt,name=terminal_resize,json=terminalResize,proto3,oneof"`
}

func (*ExecRequest_Command_) isExecRequest_Type() {}

func (*ExecRequest_StandardInput) isExecRequest_Type() {}

func (*ExecRequest_TerminalResize) isExecRequest_Type() {}

type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ExecResponse_Exit_
	//	*ExecResponse_StandardOutput
	//	*ExecResponse_StandardError
	//	*ExecResponse_Started_
	Type          isExecResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_rpc_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetType() isExecResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ExecResponse) GetExit() *ExecResponse_Exit {
	if x != nil {
		if x, ok := x.Type.(*ExecResponse_Exit_); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *ExecResponse) GetStandardOutput() *IOChunk {
	if x != nil {
		if x, ok := x.Type.(*ExecResponse_StandardOutput); ok {
			return x.StandardOutput
		}
	}
	return nil
}

func (x *ExecResponse) GetStandardError() *IOChunk {
	if x != nil {
		if x, ok := x.Type.(*ExecResponse_StandardError); ok {
			return x.StandardError
		}
	}
	return nil
}

func (x *ExecResponse) GetStarted() *ExecResponse_Started {
	if x != nil {
		if x, ok := x.Type.(*ExecResponse_Started_); ok {
			return x.Started
		}
	}
	return nil
}

type isExecResponse_Type interface {
	isExecResponse_Type()
}

type ExecResponse_Exit_ struct {
	Exit *ExecResponse_Exit `protobuf:"bytes,1,opt,name=exit,proto3,oneof"`
}

type ExecResponse_StandardOutput struct {
	StandardOutput *IOChunk `protobuf:"bytes,2,opt,name=standard_output,json=standardOutput,proto3,oneof"`
}

type ExecResponse_StandardError struct {
	StandardError *IOChunk `protobuf:"bytes,3,opt,name=standard_error,json=standardError,proto3,oneof"`
}

type ExecResponse_Started_ struct {
	Started *ExecResponse_Started `protobuf:"bytes,4,opt,name=started,proto3,oneof"`
}

func (*ExecResponse_Exit_) isExecResponse_Type() {}

func (*ExecResponse_StandardOutput) isExecResponse_Type() {}

func (*ExecResponse_StandardError) isExecResponse_Type() {}

func (*ExecResponse_Started_) isExecResponse_Type() {}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_rpc_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type IOChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOChunk) Reset() {
	*x = IOChunk{}
	mi := &file_rpc_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOChunk) ProtoMessage() {}

func (x *IOChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOChunk.ProtoReflect.Descriptor instead.
func (*IOChunk) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{3}
}

func (x *IOChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIPRequest) Reset() {
	*x = ResolveIPRequest{}
	mi := &file_rpc_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIPRequest) ProtoMessage() {}

func (x *ResolveIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIPRequest.ProtoReflect.Descriptor instead.
func (*ResolveIPRequest) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{4}
}

type ResolveIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIPResponse) Reset() {
	*x = ResolveIPResponse{}
	mi := &file_rpc_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIPResponse) ProtoMessage() {}

func (x *ResolveIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIPResponse.ProtoReflect.Descriptor instead.
func (*ResolveIPResponse) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveIPResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Signal        SignalRequest_Signal   `protobuf:"varint,2,opt,name=signal,proto3,enum=SignalRequest_Signal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_rpc_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SignalRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *SignalRequest) GetSignal() SignalRequest_Signal {
	if x != nil {
		return x.Signal
	}
	return SignalRequest_SIGNAL_UNSPECIFIED
}

type ExecRequest_Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Interactive   bool                   `protobuf:"varint,3,opt,name=interactive,proto3" json:"interactive,omitempty"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	TerminalSize  *TerminalSize          `protobuf:"bytes,5,opt,name=terminal_size,json=terminalSize,proto3" json:"terminal_size,omitempty"`
	Detach        bool                   `protobuf:"varint,6,opt,name=detach,proto3" json:"detach,omitempty"`
	Env           map[string]string      `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workdir       string                 `protobuf:"bytes,8,opt,name=workdir,proto3" json:"workdir,omitempty"`
	User          string                 `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest_Command) Reset() {
	*x = ExecRequest_Command{}
	mi := &file_rpc_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest_Command) ProtoMessage() {}

func (x *ExecRequest_Command) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest_Command.ProtoReflect.Descriptor instead.
func (*ExecRequest_Command) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ExecRequest_Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecRequest_Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest_Command) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *ExecRequest_Command) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecRequest_Command) GetTerminalSize() *TerminalSize {
	if x != nil {
		return x.TerminalSize
	}
	return nil
}

func (x *ExecRequest_Command) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

func (x *ExecRequest_Command) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest_Command) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ExecRequest_Command) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ExecResponse_Exit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse_Exit) Reset() {
	*x = ExecResponse_Exit{}
	mi := &file_rpc_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse_Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse_Exit) ProtoMessage() {}

func (x *ExecResponse_Exit) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse_Exit.ProtoReflect.Descriptor instead.
func (*ExecResponse_Exit) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ExecResponse_Exit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ExecResponse_Started struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse_Started) Reset() {
	*x = ExecResponse_Started{}
	mi := &file_rpc_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse_Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse_Started) ProtoMessage() {}

func (x *ExecResponse_Started) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse_Started.ProtoReflect.Descriptor instead.
func (*ExecResponse_Started) Descriptor() ([]byte, []int) {
	return file_rpc_agent_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ExecResponse_Started) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

var File_rpc_agent_proto protoreflect.FileDescriptor

const file_rpc_agent_proto_rawDesc = "" +
	"\n" +
	"\x0frpc/agent.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xff\x03\n" +
	"\vExecRequest\x120\n" +
	"\acommand\x18\x01 \x01(\v2\x14.ExecRequest.CommandH\x00R\acommand\x121\n" +
	"\x0estandard_input\x18\x02 \x01(\v2\b.IOChunkH\x00R\rstandardInput\x128\n" +
	"\x0fterminal_resize\x18\x03 \x01(\v2\r.TerminalSizeH\x00R\x0eterminalResize\x1a\xc8\x02\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12 \n" +
	"\vinteractive\x18\x03 \x01(\bR\vinteractive\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x122\n" +
	"\rterminal_size\x18\x05 \x01(\v2\r.TerminalSizeR\fterminalSize\x12\x16\n" +
	"\x06detach\x18\x06 \x01(\bR\x06detach\x12/\n" +
	"\x03env\x18\a \x03(\v2\x1d.ExecRequest.Command.EnvEntryR\x03env\x12\x18\n" +
	"\aworkdir\x18\b \x01(\tR\aworkdir\x12\x12\n" +
	"\x04user\x18\t \x01(\tR\x04user\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04type\"\x9b\x02\n" +
	"\fExecResponse\x12(\n" +
	"\x04exit\x18\x01 \x01(\v2\x12.ExecResponse.ExitH\x00R\x04exit\x123\n" +
	"\x0fstandard_output\x18\x02 \x01(\v2\b.IOChunkH\x00R\x0estandardOutput\x121\n" +
	"\x0estandard_error\x18\x03 \x01(\v2\b.IOChunkH\x00R\rstandardError\x121\n" +
	"\astarted\x18\x04 \x01(\v2\x15.ExecResponse.StartedH\x00R\astarted\x1a\x1a\n" +
	"\x04Exit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x1a\"\n" +
	"\aStarted\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execIdB\x06\n" +
	"\x04type\"6\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"\x1d\n" +
	"\aIOChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x12\n" +
	"\x10ResolveIPRequest\"#\n" +
	"\x11ResolveIPResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xa1\x01\n" +
	"\rSignalRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12-\n" +
	"\x06signal\x18\x02 \x01(\x0e2\x15.SignalRequest.SignalR\x06signal\"H\n" +
	"\x06Signal\x12\x16\n" +
	"\x12SIGNAL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSIGNAL_SIGTERM\x10\x01\x12\x12\n" +
	"\x0eSIGNAL_SIGKILL\x10\x022\x96\x01\n" +
	"\x05Agent\x12'\n" +
	"\x04Exec\x12\f.ExecRequest\x1a\r.ExecResponse(\x010\x01\x120\n" +
	"\x06Signal\x12\x0e.SignalRequest\x1a\x16.google.protobuf.Empty\x122\n" +
	"\tResolveIP\x12\x11.ResolveIPRequest\x1a\x12.ResolveIPResponseB5Z3github.com/cirruslabs/tart-guest-agent/internal/rpcb\x06proto3"

var (
	file_rpc_agent_proto_rawDescOnce sync.Once
	file_rpc_agent_proto_rawDescData []byte
)

func file_rpc_agent_proto_rawDescGZIP() []byte {
	file_rpc_agent_proto_rawDescOnce.Do(func() {
		file_rpc_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_agent_proto_rawDesc), len(file_rpc_agent_proto_rawDesc)))
	})
	return file_rpc_agent_proto_rawDescData
}

var file_rpc_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_agent_proto_goTypes = []any{
	(SignalRequest_Signal)(0),    // 0: SignalRequest.Signal
	(*ExecRequest)(nil),          // 1: ExecRequest
	(*ExecResponse)(nil),         // 2: ExecResponse
	(*TerminalSize)(nil),         // 3: TerminalSize
	(*IOChunk)(nil),              // 4: IOChunk
	(*ResolveIPRequest)(nil),     // 5: ResolveIPRequest
	(*ResolveIPResponse)(nil),    // 6: ResolveIPResponse
	(*SignalRequest)(nil),        // 7: SignalRequest
	(*ExecRequest_Command)(nil),  // 8: ExecRequest.Command
	nil,                          // 9: ExecRequest.Command.EnvEntry
	(*ExecResponse_Exit)(nil),    // 10: ExecResponse.Exit
	(*ExecResponse_Started)(nil), // 11: ExecResponse.Started
	(*emptypb.Empty)(nil),        // 12: google.protobuf.Empty
}
var file_rpc_agent_proto_depIdxs = []int32{
	8,  // 0: ExecRequest.command:type_name -> ExecRequest.Command
	4,  // 1: ExecRequest.standard_input:type_name -> IOChunk
	3,  // 2: ExecRequest.terminal_resize:type_name -> TerminalSize
	10, // 3: ExecResponse.exit:type_name -> ExecResponse.Exit
	4,  // 4: ExecResponse.standard_output:type_name -> IOChunk
	4,  // 5: ExecResponse.standard_error:type_name -> IOChunk
	11, // 6: ExecResponse.started:type_name -> ExecResponse.Started
	0,  // 7: SignalRequest.signal:type_name -> SignalRequest.Signal
	3,  // 8: ExecRequest.Command.terminal_size:type_name -> TerminalSize
	9,  // 9: ExecRequest.Command.env:type_name -> ExecRequest.Command.EnvEntry
	1,  // 10: Agent.Exec:input_type -> ExecRequest
	7,  // 11: Agent.Signal:input_type -> SignalRequest
	5,  // 12: Agent.ResolveIP:input_type -> ResolveIPRequest
	2,  // 13: Agent.Exec:output_type -> ExecResponse
	12, // 14: Agent.Signal:output_type -> google.protobuf.Empty
	6,  // 15: Agent.ResolveIP:output_type -> ResolveIPResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rpc_agent_proto_init() }
func file_rpc_agent_proto_init() {
	if File_rpc_agent_proto != nil {
		return
	}
	file_rpc_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecRequest_Command_)(nil),
		(*ExecRequest_StandardInput)(nil),
		(*ExecRequest_TerminalResize)(nil),
	}
	file_rpc_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecResponse_Exit_)(nil),
		(*ExecResponse_StandardOutput)(nil),
		(*ExecResponse_StandardError)(nil),
		(*ExecResponse_Started_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_agent_proto_rawDesc), len(file_rpc_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_agent_proto_goTypes,
		DependencyIndexes: file_rpc_agent_proto_depIdxs,
		EnumInfos:         file_rpc_agent_proto_enumTypes,
		MessageInfos:      file_rpc_agent_proto_msgTypes,
	}.Build()
	File_rpc_agent_proto = out.File
	file_rpc_agent_proto_goTypes = nil
	file_rpc_agent_proto_depIdxs = nil
}
